# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Add issue or pull request to project

on:
  issues:
    types:
      - opened
      - reopened
  # pull_request:
  #   types:
  #     - opened
  #     - reopened

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add issue or pull request to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd  # v2
        with:
          project-url: https://github.com/orgs/scio-labs/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
